from io import StringIO
import os
from pathlib import Path
from tempfile import TemporaryDirectory
import unittest

from fastproto_compiler.cli import run
from fastproto_compiler.generator import generate_code

SCHEMA = """
namespace sample {
message Point(1) {
    x: int32;
    y: int32;
}

message Greeting(2) {
    text: string;
}
}
"""


class FastprotoCompilerTests(unittest.TestCase):
    def test_generated_header_embeds_runtime_by_default(self):
        header = generate_code(SCHEMA, source_name="sample.fastproto")

        self.assertIn("#include <span>", header)
        self.assertIn("#ifndef FASTPROTO_RUNTIME_HPP_INCLUDED", header)
        self.assertNotIn('#include "fastproto/fastproto.hpp"', header)
        self.assertIn("FASTPROTO_BEGIN_STRUCT_DEFINITION(sample, Point, 1)", header)
        self.assertIn("FASTPROTO_STRING_FIELD(text)", header)

    def test_cli_writes_explicit_output(self):
        with TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            schema_path = tmp_path / "sample.fastproto"
            header_path = tmp_path / "sample.hpp"
            schema_path.write_text(SCHEMA)

            exit_code = run(["-o", str(header_path), str(schema_path)])

            self.assertEqual(exit_code, 0)
            self.assertIn(
                "FASTPROTO_BEGIN_STRUCT_DEFINITION(sample, Point, 1)",
                header_path.read_text(),
            )

    def test_cli_defaults_single_input_to_stdout(self):
        with TemporaryDirectory() as tmp:
            schema_path = Path(tmp) / "sample.fastproto"
            schema_path.write_text(SCHEMA)
            stdout = StringIO()

            exit_code = run([str(schema_path)], stdout=stdout)

            self.assertEqual(exit_code, 0)
            self.assertIn("Generated by fastproto", stdout.getvalue())

    def test_cli_generates_python_package_directory(self):
        with TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            schema_path = tmp_path / "sample.fastproto"
            schema_path.write_text(SCHEMA)
            old_cwd = Path.cwd()
            try:
                os.chdir(tmp_path)
                exit_code = run(["--python-out", "fastproto_example", str(schema_path)])
            finally:
                os.chdir(old_cwd)

            package_root = tmp_path / "fastproto_example"

            self.assertEqual(exit_code, 0)
            self.assertTrue((package_root / "pyproject.toml").exists())
            self.assertTrue((package_root / "CMakeLists.txt").exists())
            self.assertTrue((package_root / "include" / "generated.hpp").exists())
            self.assertTrue(
                (package_root / "src" / "fastproto_example_bindings.cpp").exists()
            )
            self.assertTrue(
                (package_root / "fastproto_example" / "__init__.py").exists()
            )
            self.assertIn(
                "PYBIND11_MODULE(_fastproto_example, m)",
                (package_root / "src" / "fastproto_example_bindings.cpp").read_text(),
            )
            self.assertIn(
                'auto module_sample = m.def_submodule("sample");',
                (package_root / "src" / "fastproto_example_bindings.cpp").read_text(),
            )
            self.assertIn(
                "from . import _fastproto_example as _native",
                (package_root / "fastproto_example" / "__init__.py").read_text(),
            )

    def test_cli_rejects_output_with_python_package_mode(self):
        with TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            schema_path = tmp_path / "sample.fastproto"
            schema_path.write_text(SCHEMA)
            stderr = StringIO()

            exit_code = run(
                [
                    "--python-out",
                    "fastproto_example",
                    "-o",
                    str(tmp_path / "ignored"),
                    str(schema_path),
                ],
                stderr=stderr,
            )

            self.assertEqual(exit_code, 1)
            self.assertIn(
                "--output cannot be used with --python-out", stderr.getvalue()
            )

    def test_cli_reports_invalid_python_package_name(self):
        with TemporaryDirectory() as tmp:
            schema_path = Path(tmp) / "sample.fastproto"
            schema_path.write_text(SCHEMA)
            stderr = StringIO()

            exit_code = run(
                ["--python-out", "bad-name", str(schema_path)],
                stderr=stderr,
            )

            self.assertEqual(exit_code, 1)
            self.assertIn(
                "python package name must be a valid Python identifier",
                stderr.getvalue(),
            )


if __name__ == "__main__":
    unittest.main()
