from io import StringIO
from pathlib import Path
from tempfile import TemporaryDirectory
import unittest

from fastproto_compiler.cli import run
from fastproto_compiler.generator import generate_code

SCHEMA = """
namespace sample {
message Point(1) {
    x: int32;
    y: int32;
}

message Greeting(2) {
    text: string;
}
}
"""


class FastprotoCompilerTests(unittest.TestCase):
    def test_generated_header_embeds_runtime_by_default(self):
        header = generate_code(SCHEMA, source_name="sample.fastproto")

        self.assertIn("#include <span>", header)
        self.assertIn("#ifndef FASTPROTO_RUNTIME_HPP_INCLUDED", header)
        self.assertNotIn('#include "fastproto/fastproto.hpp"', header)
        self.assertIn("FASTPROTO_BEGIN_STRUCT_DEFINITION(sample, Point, 1)", header)
        self.assertIn("FASTPROTO_STRING_FIELD(text)", header)

    def test_cli_writes_explicit_output(self):
        with TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            schema_path = tmp_path / "sample.fastproto"
            header_path = tmp_path / "sample.hpp"
            schema_path.write_text(SCHEMA)

            exit_code = run(["-o", str(header_path), str(schema_path)])

            self.assertEqual(exit_code, 0)
            self.assertIn(
                "FASTPROTO_BEGIN_STRUCT_DEFINITION(sample, Point, 1)",
                header_path.read_text(),
            )

    def test_cli_defaults_single_input_to_stdout(self):
        with TemporaryDirectory() as tmp:
            schema_path = Path(tmp) / "sample.fastproto"
            schema_path.write_text(SCHEMA)
            stdout = StringIO()

            exit_code = run([str(schema_path)], stdout=stdout)

            self.assertEqual(exit_code, 0)
            self.assertIn("Generated by fastproto", stdout.getvalue())


if __name__ == "__main__":
    unittest.main()
