// Generated by fastproto python bindings from example.fastproto. Do not edit by
// hand.
#include "generated.hpp"

#ifndef FASTPROTO_PYRUNTIME_HPP_INCLUDED
#define FASTPROTO_PYRUNTIME_HPP_INCLUDED

#include <cstddef>
#include <cstdint>
#include <span>
#include <string>
#include <utility>
#include <vector>

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

namespace fastproto::python {

inline py::bytes bytes_from_span(std::span<const std::byte> buffer) {
    return py::bytes(reinterpret_cast<const char*>(buffer.data()),
                     buffer.size());
}

inline std::span<const std::byte> span_from_buffer(py::buffer buffer) {
    py::buffer_info info = buffer.request();
    if (info.ndim != 1 || info.itemsize != 1) {
        throw py::value_error("expected a one-dimensional byte buffer");
    }
    return std::span<const std::byte>(
        reinterpret_cast<const std::byte*>(info.ptr),
        static_cast<size_t>(info.size));
}

} // namespace fastproto::python

#define FASTPROTO_PYTHON_BEGIN_FACTORY_DEFINITION(ns, name)                    \
    class name##Factory {                                                      \
      private:                                                                 \
        fastproto::Factory<fastproto::generated::ns::name> factory_;           \
                                                                               \
      public:                                                                  \
        py::bytes serialize() {                                                \
            return fastproto::python::bytes_from_span(factory_.serialize());   \
        }

#define FASTPROTO_PYTHON_FACTORY_BUILTIN_FIELD(type, name)                     \
    void set_##name(type value) { factory_.set_##name(value); }                \
    type name() const { return factory_.get_##name(); }

#define FASTPROTO_PYTHON_FACTORY_STRING_FIELD(name)                            \
    void set_##name(const std::string& value) { factory_.set_##name(value); }  \
    std::string name() const { return std::string(factory_.get_##name()); }

#define FASTPROTO_PYTHON_FACTORY_BUILTIN_ARRAY_FIELD(type, name)               \
    void add_##name(const type& value) { factory_.add_##name(value); }         \
    void clear_##name() { factory_.clear_##name(); }                           \
    size_t size_##name() const { return factory_.size_##name(); }              \
    type get_##name(size_t index) const { return factory_.get_##name(index); }

#define FASTPROTO_PYTHON_FACTORY_MESSAGE_ARRAY_FIELD(view_type, name)          \
    view_type##MutableView add_##name() {                                      \
        return view_type##MutableView(factory_.add_##name());                  \
    }                                                                          \
    void clear_##name() { factory_.clear_##name(); }

#define FASTPROTO_PYTHON_FACTORY_MESSAGE_FIELD(view_type, name)                \
    view_type##MutableView edit_##name() {                                     \
        return view_type##MutableView(factory_.edit_##name());                 \
    }

#define FASTPROTO_PYTHON_END_FACTORY_DEFINITION()                              \
    }                                                                          \
    ;

#define FASTPROTO_PYTHON_BEGIN_PARSER_DEFINITION(ns, name)                     \
    class name##Parser {                                                       \
      private:                                                                 \
        py::object owner_;                                                     \
        fastproto::Parser<fastproto::generated::ns::name> parser_;             \
                                                                               \
      public:                                                                  \
        explicit name##Parser(py::buffer input) : owner_(input) {              \
            parser_.parse(fastproto::python::span_from_buffer(input));         \
        }

#define FASTPROTO_PYTHON_PARSER_BUILTIN_FIELD(type, name)                      \
    type name() const { return parser_.get_##name(); }

#define FASTPROTO_PYTHON_PARSER_STRING_FIELD(name)                             \
    std::string name() const { return std::string(parser_.get_##name()); }

#define FASTPROTO_PYTHON_PARSER_BUILTIN_ARRAY_FIELD(type, name)                \
    std::vector<type> name() const {                                           \
        std::vector<type> out;                                                 \
        out.reserve(parser_.size_##name());                                    \
        for (size_t index = 0; index < parser_.size_##name(); ++index) {       \
            out.push_back(parser_.get_##name(index));                          \
        }                                                                      \
        return out;                                                            \
    }

#define FASTPROTO_PYTHON_PARSER_MESSAGE_ARRAY_FIELD(view_type, name)           \
    py::list name() const {                                                    \
        py::list out;                                                          \
        for (const auto& item : parser_.get_##name()) {                        \
            out.append(view_type##View(&item, owner_));                        \
        }                                                                      \
        return out;                                                            \
    }

#define FASTPROTO_PYTHON_PARSER_MESSAGE_FIELD(view_type, name)                 \
    view_type##View name() const {                                             \
        return view_type##View(&parser_.get_##name(), owner_);                 \
    }

#define FASTPROTO_PYTHON_END_PARSER_DEFINITION()                               \
    }                                                                          \
    ;

#define FASTPROTO_PYTHON_BEGIN_VIEW_DEFINITION(ns, name)                       \
    class name##View {                                                         \
      private:                                                                 \
        const fastproto::generated::ns::name* message_;                        \
        py::object owner_;                                                     \
                                                                               \
      public:                                                                  \
        name##View(const fastproto::generated::ns::name* message,              \
                   py::object owner)                                           \
            : message_(message), owner_(std::move(owner)) {}

#define FASTPROTO_PYTHON_VIEW_BUILTIN_FIELD(type, name)                        \
    type name() const { return message_->get_##name(); }

#define FASTPROTO_PYTHON_VIEW_STRING_FIELD(name)                               \
    std::string name() const { return std::string(message_->get_##name()); }

#define FASTPROTO_PYTHON_VIEW_MESSAGE_FIELD(view_type, name)                   \
    view_type##View name() const {                                             \
        return view_type##View(&message_->get_##name(), owner_);               \
    }

#define FASTPROTO_PYTHON_END_VIEW_DEFINITION()                                 \
    }                                                                          \
    ;

#define FASTPROTO_PYTHON_BEGIN_MUTABLE_VIEW_DEFINITION(ns, name)               \
    class name##MutableView {                                                  \
      private:                                                                 \
        fastproto::generated::ns::name* message_;                              \
                                                                               \
      public:                                                                  \
        explicit name##MutableView(fastproto::generated::ns::name* message)    \
            : message_(message) {}

#define FASTPROTO_PYTHON_MUTABLE_VIEW_BUILTIN_FIELD(type, name)                \
    void set_##name(type value) { message_->set_##name(value); }               \
    type name() const { return message_->get_##name(); }

#define FASTPROTO_PYTHON_MUTABLE_VIEW_MESSAGE_FIELD(view_type, name)           \
    view_type##MutableView edit_##name() {                                     \
        return view_type##MutableView(message_->edit_##name());                \
    }

#define FASTPROTO_PYTHON_END_MUTABLE_VIEW_DEFINITION()                         \
    }                                                                          \
    ;

#define FASTPROTO_PYTHON_BIND_FACTORY_BEGIN(module, name)                      \
    py::class_<name##Factory>(module, #name "Factory").def(py::init<>())

#define FASTPROTO_PYTHON_BIND_FACTORY_END(name)                                \
    .def("serialize", &name##Factory::serialize);

#define FASTPROTO_PYTHON_BIND_PARSER_BEGIN(module, name)                       \
    py::class_<name##Parser>(module, #name "Parser").def(py::init<py::buffer>())

#define FASTPROTO_PYTHON_BIND_PARSER_END() ;

#define FASTPROTO_PYTHON_BIND_VIEW_BEGIN(module, name)                         \
    py::class_<name##View>(module, #name "View")

#define FASTPROTO_PYTHON_BIND_VIEW_END() ;

#define FASTPROTO_PYTHON_BIND_MUTABLE_VIEW_BEGIN(module, name)                 \
    py::class_<name##MutableView>(module, #name "MutableView")

#define FASTPROTO_PYTHON_BIND_MUTABLE_VIEW_END() ;

#define FASTPROTO_PYTHON_BIND_PROPERTY(cls, name)                              \
    .def_property(#name, &cls::name, &cls::set_##name)

#define FASTPROTO_PYTHON_BIND_READONLY_PROPERTY(cls, name)                     \
    .def_property_readonly(#name, &cls::name)

#define FASTPROTO_PYTHON_BIND_METHOD(cls, name) .def(#name, &cls::name)

#define FASTPROTO_PYTHON_BIND_METHOD_WITH_ARG(cls, name, arg_name)             \
    .def(#name, &cls::name, py::arg(arg_name))

#endif // FASTPROTO_PYRUNTIME_HPP_INCLUDED

FASTPROTO_PYTHON_BEGIN_MUTABLE_VIEW_DEFINITION(my_namespace, SimpleMessage)
FASTPROTO_PYTHON_MUTABLE_VIEW_BUILTIN_FIELD(int32_t, simple_int_field)
FASTPROTO_PYTHON_END_MUTABLE_VIEW_DEFINITION()

FASTPROTO_PYTHON_BEGIN_VIEW_DEFINITION(my_namespace, SimpleMessage)
FASTPROTO_PYTHON_VIEW_BUILTIN_FIELD(int32_t, simple_int_field)
FASTPROTO_PYTHON_END_VIEW_DEFINITION()

FASTPROTO_PYTHON_BEGIN_FACTORY_DEFINITION(my_namespace, SimpleMessage)
FASTPROTO_PYTHON_FACTORY_BUILTIN_FIELD(int32_t, simple_int_field)
FASTPROTO_PYTHON_END_FACTORY_DEFINITION()

FASTPROTO_PYTHON_BEGIN_PARSER_DEFINITION(my_namespace, SimpleMessage)
FASTPROTO_PYTHON_PARSER_BUILTIN_FIELD(int32_t, simple_int_field)
FASTPROTO_PYTHON_END_PARSER_DEFINITION()

FASTPROTO_PYTHON_BEGIN_FACTORY_DEFINITION(
    my_namespace::my_sub_namespace::my_next_sub_namespace, MessageWithString)
FASTPROTO_PYTHON_FACTORY_BUILTIN_FIELD(int32_t, my_int_field)
FASTPROTO_PYTHON_FACTORY_STRING_FIELD(my_string_field)
FASTPROTO_PYTHON_END_FACTORY_DEFINITION()

FASTPROTO_PYTHON_BEGIN_PARSER_DEFINITION(
    my_namespace::my_sub_namespace::my_next_sub_namespace, MessageWithString)
FASTPROTO_PYTHON_PARSER_BUILTIN_FIELD(int32_t, my_int_field)
FASTPROTO_PYTHON_PARSER_STRING_FIELD(my_string_field)
FASTPROTO_PYTHON_END_PARSER_DEFINITION()

FASTPROTO_PYTHON_BEGIN_FACTORY_DEFINITION(my_namespace, MessageWithArray)
FASTPROTO_PYTHON_FACTORY_MESSAGE_ARRAY_FIELD(SimpleMessage, my_array_field)
FASTPROTO_PYTHON_FACTORY_BUILTIN_ARRAY_FIELD(int32_t, my_builtin_array_field)
FASTPROTO_PYTHON_END_FACTORY_DEFINITION()

FASTPROTO_PYTHON_BEGIN_PARSER_DEFINITION(my_namespace, MessageWithArray)
FASTPROTO_PYTHON_PARSER_MESSAGE_ARRAY_FIELD(SimpleMessage, my_array_field)
FASTPROTO_PYTHON_PARSER_BUILTIN_ARRAY_FIELD(int32_t, my_builtin_array_field)
FASTPROTO_PYTHON_END_PARSER_DEFINITION()

PYBIND11_MODULE(_fastproto_example, m) {
    m.doc() = "Generated fastproto bindings";

    FASTPROTO_PYTHON_BIND_MUTABLE_VIEW_BEGIN(m, SimpleMessage)
    FASTPROTO_PYTHON_BIND_PROPERTY(SimpleMessageMutableView, simple_int_field)
    FASTPROTO_PYTHON_BIND_MUTABLE_VIEW_END()

    FASTPROTO_PYTHON_BIND_VIEW_BEGIN(m, SimpleMessage)
    FASTPROTO_PYTHON_BIND_READONLY_PROPERTY(SimpleMessageView, simple_int_field)
    FASTPROTO_PYTHON_BIND_VIEW_END()

    FASTPROTO_PYTHON_BIND_FACTORY_BEGIN(m, SimpleMessage)
    FASTPROTO_PYTHON_BIND_PROPERTY(SimpleMessageFactory, simple_int_field)
    FASTPROTO_PYTHON_BIND_FACTORY_END(SimpleMessage)

    FASTPROTO_PYTHON_BIND_PARSER_BEGIN(m, SimpleMessage)
    FASTPROTO_PYTHON_BIND_READONLY_PROPERTY(SimpleMessageParser,
                                            simple_int_field)
    FASTPROTO_PYTHON_BIND_PARSER_END()

    FASTPROTO_PYTHON_BIND_FACTORY_BEGIN(m, MessageWithString)
    FASTPROTO_PYTHON_BIND_PROPERTY(MessageWithStringFactory, my_int_field)
    FASTPROTO_PYTHON_BIND_PROPERTY(MessageWithStringFactory, my_string_field)
    FASTPROTO_PYTHON_BIND_FACTORY_END(MessageWithString)

    FASTPROTO_PYTHON_BIND_PARSER_BEGIN(m, MessageWithString)
    FASTPROTO_PYTHON_BIND_READONLY_PROPERTY(MessageWithStringParser,
                                            my_int_field)
    FASTPROTO_PYTHON_BIND_READONLY_PROPERTY(MessageWithStringParser,
                                            my_string_field)
    FASTPROTO_PYTHON_BIND_PARSER_END()

    FASTPROTO_PYTHON_BIND_FACTORY_BEGIN(m, MessageWithArray)
    FASTPROTO_PYTHON_BIND_METHOD(MessageWithArrayFactory, add_my_array_field)
    FASTPROTO_PYTHON_BIND_METHOD(MessageWithArrayFactory, clear_my_array_field)
    FASTPROTO_PYTHON_BIND_METHOD(MessageWithArrayFactory,
                                 add_my_builtin_array_field)
    FASTPROTO_PYTHON_BIND_METHOD(MessageWithArrayFactory,
                                 clear_my_builtin_array_field)
    FASTPROTO_PYTHON_BIND_METHOD(MessageWithArrayFactory,
                                 size_my_builtin_array_field)
    FASTPROTO_PYTHON_BIND_METHOD_WITH_ARG(MessageWithArrayFactory,
                                          get_my_builtin_array_field, "index")
    FASTPROTO_PYTHON_BIND_FACTORY_END(MessageWithArray)

    FASTPROTO_PYTHON_BIND_PARSER_BEGIN(m, MessageWithArray)
    FASTPROTO_PYTHON_BIND_READONLY_PROPERTY(MessageWithArrayParser,
                                            my_array_field)
    FASTPROTO_PYTHON_BIND_READONLY_PROPERTY(MessageWithArrayParser,
                                            my_builtin_array_field)
    FASTPROTO_PYTHON_BIND_PARSER_END()
}
